spring:
  application:
    name: PAYMENTSERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: Venky@123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://localhost:9296


management:
  tracing:
    zipkin:
      enabled: false

server:
  port: 8083
